// CMYK → sRGB conversion. PDF viewers convert DeviceCMYK through an ICC profile (pure cyan shows as a soft blue, not
// as 00FFFF); the naive 1 − (c + k) formula gives visibly different, over-saturated colours. This table samples such a
// profile-based conversion on a 9-step grid per ink and is interpolated quadrilinearly (mean error ≈ 1.4/255).

const GRID = 9;
// 9⁴ RGB triplets, cyan varying slowest, then magenta, yellow and black.
const LUT_B64 =
    "////4eLjxsjKrK6wk5WYfH6AY2RmR0dJIx8g//3k4+DLyMe1ra2elJSIfXxyY2NbR0Y/IR4Z//vM5N+2ycajrqyOlZN5fXtmZGJQRkU3IB0R//my5d2gysSPr6p8lZJqfXpZZGFFRkQuHxwI//eZ5t" +
    "yJy8N6r6lqlZBafnlLZGA6RkQkHhwA//Z/59pzy8FmsKhZlo9Lfng9ZGAuRkMaHRsA//Rg59lXzMBNsKdDlo43fngsZF8eRkIKHBsA//M16NczzL8usKYnlo0efncUZF4GRkIAHBoA//IA6NcAzL4A" +
    "sKUAlo0AfnYAZF4ARkEAGxoA/OTu38rVxbO9q5ylkoWOe3B4Y1lfRz5DIxca/eLV4Mm/xrKqrJuVk4R/fG9rY1hVRj06IhYT/+C/4cirx7GZrJqFk4NyfG5fY1dLRjwyIRUL/9+o4saXyLCGrZl1lI" +
    "JkfG1TY1ZARjwpIBUC/92R48WCyK5zrZhklIFVfGxGY1Y1RjsgHxQA/9x648NtyK1hrZZUlIBGfGw5Y1UqRjoWHhQA/9td5MJUyaxKrpU/lIA0fGspY1QbRToGHhMA/9k45ME0yasurpUmlH8dfGoT" +
    "Y1QERToAHRMA/9kA5MAAyaoCrpQAlH4AfGoAY1QARTkAHRMA+cvf3LXHw6CyqYubkXeFe2NwYk5ZRzU9Iw0V+snI3rOzxJ+gqoqMknZ3e2NkYk1PRjQ1Ig0N+8i03rKhxZ6Qq4p9knVre2JZYk1FRj" +
    "QuIQwE/Mef37GOxZ1/q4luknRde2FNYkw7RjMlIQwA/caJ4LB7xpxtq4deknNQe2BBYkwxRjMcIAwA/cR04K9oxptcq4dPknNCe2A1YksmRTIRHwsA/sNa4K5QxppHrIY8knIxe18mYksYRTIBHwsA" +
    "/sI64a00xpktrIUlknEbe14RYkoBRTIAHgsA/8IN4awOxpkLrIQEknEAe14AYkoARTEAHgsA9rLQ2p66wYylqHqRkGd8elZoYkNSRis4IwEP97C7252nwoyVqXmCkWdvelZdYkJJRiswIgEG+K+o3J" +
    "yXw4uGqXl1kWZkelVTYkJARiopIgEA+a6V3JuFw4p3qXhnkWZXelRIYUE2RSogIQEA+q2B3Ztzw4lmqXdYkWVKelQ8YUEsRSoXIQEA+q1t3Zpiw4hWqXZKkWQ9elMxYUAiRSoMIAEA+qxW3ZlNxIdD" +
    "qnU5kWQuelMiYUAURSkAIAEA+6s63pgzxIcsqnUkkWMaelIPYUAARSkAHwEA+6oY3pgWxIYRqnQIkWMAelIAYT8ARSkAHwEA9JrB2Iisv3iap2iGj1hzeUlgYTdMRiEzIwAI9Ziu2YibwHiLp2h5j1" +
    "hneUhWYTdDRiErIwAA9Zed2YeMwXh9qGhtkFdceUhMYTY6RiAkIgAA9peL2oZ8wXduqGdgj1dReUdCYTYxRSAcIgAA9pZ52oVswXZfqGZSj1ZFeUc3YTYoRSASIQAA95Vn2oVcwXZRqGZFj1Y5eUct" +
    "YDYeRSAHIQAA95VS24RJwXU/qGU1j1UqeUYfYDUQRSAAIQAA95Q524QywXQrqGUij1UYeUYMYDUARSAAIAAA95Md24MZwXQUqGQLj1UAeUYAYDUARSAAIAAA8oK01nOhvmaPpld9jklreDtZYStGRh" +
    "UtIwAC84Gi13ORv2WBpldwjklgeDtPYSs9RhUmIwAA84GS13KDv2V0pldljklVeDtGYSs1RRUfIgAA84CC2HJ0v2VnpldZjkhLeDs9YCstRRYXIgAA9IBx2HFlv2RZplZMjkg/eDozYCsjRRYNIgAA" +
    "9H9h2HFWv2RMplZAjkg0eDopYCsaRRYCIQAA9H9N2HFFv2M8plUyjkgneDocYCsMRBYAIQAA9X432HAwv2MpplUgjkcWeDoJYCsARBYAIQAA9X4g2XAbv2MWplUNjkcBeDoAYCsARBYAIQAA8Gem1F" +
    "uUvFCEpENzjTdieCtSYRs/RgIoIwAA8GeW1VuGvVB3pURojTdYeCtIYBw3RQMhIwAA8WeH1lt5vVBspURdjThOdytAYBwwRQQaIwAA8Wd41ltrvVBfpURSjThEdys3YB0oRQUSIgAA8WZp1lpevU9T" +
    "pURGjTg6dysuXx0fRQYHIgAA8mZb1lpQvU9GpUM7jTgwdywkXx0VRAcAIgAA8mZJ1lpBvU84pUQujTgjdywYXx4HRAgAIgAA8mY11lovvk8opEQfjTgUdywHXx4ARAkAIgAA8mUi1lodvU8XpEQOjT" +
    "gCdywAXx4ARAkAIQAA7kWZ0zyIuzN5oylpjR5adxJKYAA5RgAiIwAA7kWJ0zx7vDRtpCpfjB9QdxNCYAExRQAbIwAA70Z81D1vvDRjpCtVjCBHdxQ6XwMqRQAUIwAA70dv1D1jvDVXoytLjCE+dhYx" +
    "XwUiRAAMIwAA70di1D5XvDVMoyxAjCI1dhcoXwYaRAABIgAA70dU1D5LvDZBoyw2jCIrdhcgXwgQRAAAIgAA70dF1D88vDY0oy0qjCMgdhgUXgkDRAAAIgAA70gz1D8tvDcmoy4djCQSdhkEXgoARA" +
    "AAIgAA70gj1D8evDcZoy4QiyQDdhoAXgsARAAAIgAA7ACM0QB9ugBvogBgjABRdwBDYAAyRQAdIwAA7QF+0gBwugBkowBWjABIdgA7XwArRQAWIwAA7Qly0gFmugBaogBNiwBAdgAzXwAkRQAOIwAA" +
    "7RBm0gdbugBQogBEiwA4dgAsXwAdRAAFIwAA7RRa0g1QugVGogA7iwAvdQAkXgAVRAAAIwAA7RdO0hFFugo8ogEyiwAndQAbXgALRAAAIwAA7RlB0hQ5ug4xogUniwAddQAQXgAARAAAIwAA7Rsx0h" +
    "YruhEkogkbiwAQdQACXgAARAAAIgAA7Rwk0hgfuhMZogwQiwIEdQAAXgAARAAAIgAA2/H9wtbhq77Jlaavf46Xand/VF9mO0NIGBwh3e/ixNXKrr20l6SdgI2HbHZyVV5bO0I/Fxsa3+7LxtO1r7yi" +
    "mKONgYx5bHZmVV1QO0E3FhsT4eyyx9KgsLqPmaJ8gotqbXVZVl1FO0EuFBoK4+qaydCKsbl7maFrgolbbXRLVlw6O0AlExoA5OmCys90srdomqBag4hMbXM+VlsvO0AbEhkA5uhly85bs7ZQmp5Fg4" +
    "c6bXIuVlohOz8NEhkA5+ZBzM07s7U0m54sg4cjbnEaVloNOz8AERkA6OYTzcwUtLUSm50Ng4YFbnEAVlkAOj4AEBgA2tjswcDTq6u8lZWkf3+Na2t3VVRfPDpDGRQb3NbUxL++raqplpSUgH5/bGpr" +
    "VVRUOzk6GBMU3tW+xb6rrqmYl5OFgX1ybGlfVVNLOzkyFxMN4NOoxryXr6eGmJJ1gXxkbGhTVlJAOzgqFhID4dKSx7uCsKZ0mJBlgntVbGdHVlI2OzghFRIA4tF8yLpvsKVimZBVgnpHbWc6VlErOz" +
    "cXFRIA49BhyblXsaRNmY9Cgno3bWYrVlAeOzcJFBEA5M9Cyrg7sqMzmY4rgnkibWUYVlAKOzcAExEA5c4dyrgasqMWmY0QgngHbWUAVlAAOzYAExEA2cDdwazGq5mxlYWaf3GEa19wVUpZPDI+GgkW" +
    "27/Hw6uyrZifloSLgHF3bF5kVUpPPDE2GQkP3b6zxKqhrpeQl4R9gXBrbF5ZVklGPDEuGAkG3r2fxamOrpZ/l4JugW9ebF1OVkk8PDAmGAkA37yKxah7r5Vul4FfgW5QbFxCVkgyOzAdFwkA4Lt2xq" +
    "dpr5RdmIFQgW5DbFs2VUgnOzATFgkA4bpex6ZTsJNJmIA/gW0zbFsoVUcaOy8EFgkA4blByKU6sJIymH8qgWwgbFoWVUcHOy8AFQkA4rkjyKUesJIZmH8SgWwJbFoAVUYAOy8AFQkA2KnOwJe4qoal" +
    "lHWQf2N7a1JoVT9SPCg4GwAR2qi6wpamrIaUlXSCgGNvbFJdVj9JPCgwGgAI26eow5WWrIWGlnN1gGJjbFFTVj9APCgpGQAA3KaVw5WFrYR3lnNngGFXbFFIVT43PCghGQAA3aaCxJR0rYNnlnJZgG" +
    "FLbFA9VT4tPCcYGAAA3aVvxJNjroJYlnFLgGA/bFAyVT4jOycOGAAA3qRZxZJProJFl3A7gF8wbE8lVT0XOycAFwAA36NAxZI4roEwl3AogF8ebE8TVT0EOycAFwAA36MmxpEgr4Ebl28TgF4JbE4A" +
    "VT0AOycAFwAA15LAv4KsqnSZlGSGf1Rza0VgVjRMPR4zGwAL2JGtwIKbq3OKlWR5f1Rna0VWVjRDPB4sGwAC2ZGcwYGMq3N9lWNtgFRca0VMVTQ7PB4kGgAA2pCLwoF8rHJvlWNggFNRa0RCVTQyPB" +
    "4dGgAA25B6woBtrHJglWJTf1NFa0Q4VTMpPB4UGQAA249pw4BdrHFSlWJGf1M6a0QuVTMfOx4JGQAA3I9Vw39LrXFBlmE3gFIsa0MhVTMTOx4AGAAA3Y4+xH82rXAulmEmgFIca0MRVTMBOx4AGAAA" +
    "3Y4oxH4irXAblmATf1EJa0MAVTMAOx4AGAAA1nyzvm+gqWKPk1R9f0ZrazhZVShGPRIuHAAF13yhv26RqmKBlFRwf0ZgazlPVSk9PBMnGwAA2HySwG6Dq2J0lFRlf0ZWazhHVSk2PBMgGwAA2XuCwW" +
    "50q2FnlFRZf0ZLazg9VSktPBMYGgAA2XtywW1mq2FalFNNf0ZAazgzVSkkPBQPGgAA2ntjwW1Yq2BNlFNCf0U2azgqVSkbOxQEGgAA2npQwm1Hq2A+lVM0f0UpajgeVSkPOxQAGQAA23o8wmw0q2As" +
    "lVIkf0UaajgOVCkAOxUAGQAA23kowmwirF8clVITf0UIajgAVCkAOxUAGQAA1WOmvViUqE2Ek0FzfjViaylSVRlAPQApHAAA1mOVv1iGqU13lEJofzZYaylJVRo4PQEiHAAA12OHv1h5qk5slEJdfj" +
    "ZPaypBVRswPAIbGwAA12R5v1hsqk1glEJTfjZFaio4VRsoPAMTGwAA2GNqwFhfqk1UlEJHfjY7aiovVRwgPAQJGwAA2GNcwFhSqk1IlEI9fjYxaiomVBwXPAUAGgAA2GNMwFhDqk06lEIwfjYlaioa" +
    "VBwKOwYAGgAA2WM5wFgyqk0qlEIifjYXaioLVB0AOwcAGgAA2WMpwVgiqk0clEITfjYIaisAVB0AOwcAGgAA1ESYvDuIqDJ5kyhpfh1aahFKVQA5PQAjHQAA1UWKvjx7qTNukypffh9QahNCVQEyPQ" +
    "AdHAAA1kZ9vj1wqTRjkypWfiBIahQ6VQMrPAAWHAAA1kZwvj1kqTVYkytMfiE/ahYyVQUjPAAOGwAA1kdjvj5YqTVNkyxCfSI2ahcqVAYbPAAEGwAA10dWvj5MqTZCkyw4fSItahchVAgSPAAAGwAA" +
    "10dHvz8+qTY2ky0sfSMiaRgWVAkGOwAAGwAA10c3vz8wqTYoky0ffSMVaRkIVAoAOwAAGwAA10cpvz8iqTccky4TfSQHaRkAVAsAOwAAGwAA0w6MvAR9pwBvkgBgfgBSagBDVQAzPQAeHQAA1BJ/vQ" +
    "pxqABkkgBXfgBJagA8VQAsPQAXHAAA1RZzvQ9nqAZbkgBOfQBBagA1VQAmPAAQHAAA1RpovRNcqAtRkgFFfQA5agAtVAAePAAHHAAA1R1cvRZRqA9HkgU8fQAxaQAlVAAXPAAAHAAA1R9QvRhHqBI9" +
    "kggzfQAoaQAdVAAOOwAAHAAA1iBDvho7qBQykgspfQEeaQATVAACOwAAGwAA1iE1vhwuqBYmkg4dfQMTaQAFVAAAOwAAGwAA1iIpvh0iqBcbkg8TfQUGaQAAUwAAOwAAGwAAueX6pMzgkrbHfp6ua4" +
    "eWWnJ+RltlLz9IDBohvePgqMvJlbSzgZ2dbYaGW3FxR1paLz8/Chkav+LKqsm1l7OhgpyNb4V5XHBlSFlQLz43CBkUwuCyrMigmLKPg5t8b4RqXW9ZSFhGLz4vBxgLxN+brcaLmbB7hJlscINcXW5M" +
    "SFg7MD0mBhgCxt6Er8V2mq9phZhbcYJNXW5ASVcwMD0dBRgAx9xpsMRem65ThpdIcYE8Xm0wSVYjMDwQBBgAydxKssNCnK06hpYxcoEoXmweSVYRMDwAAxcAytsqs8Mlna0gh5YacoASXmwHSVUALz" +
    "sAAhcAus3qprfRk6O7gI6jbXqMW2Z2SFBfMTdDDhEcvszTqba9lqKogo2Tb3l+XGVqSFBUMTc6DREVwMu+q7Wql6GYg4yEb3hxXWVfSU9LMTYzDBAOwsqorLSXmKCGhIt1cHdkXWRTSU9BMTYqCxAF" +
    "xMiSrrODmZ91hYplcXZWXmNHSU42MTUiCRAAxcd+r7Jwmp5jhYlWcXVJXmI7SU0sMTUYCRAAx8ZlsLFam51PhohEcXQ4XmItSU0fMTULCBAAyMVJsbBAnJw4hogvcnQmXmEcSUwOMTQABxAAycUtsq" +
    "8nnJwhh4cacnMSXmEHSUwAMTQABxAAu7fbp6TFlZKwgX+abm2EXFtvSUdZMi8+EAYXvrfGqqSxl5Keg3+Kb2x2XVpkSUZPMi82DwYQwLazq6OgmJGPhH59cGtrXlpZSUZGMi4uDgYIwrWfrKKOmZB/" +
    "hH1ucGteXllOSkU8Mi4mDQcAw7SLraF8mY9uhXxgcWpRXlhCSkUyMi4eDAcAxLN3rqBqmo5ehXtRcWlEXlg3SkUoMS0UDAcAxrJhr59Wm41MhntBcWg1XlcqSkQcMS0HCwcAx7FHsJ4+m4w2hnotcW" +
    "gkXlcaSkQLMS0ACgcAyLEvsZ4onIwhhnkacmcRXlYGSkQAMS0ACgcAvKHNqJG3lYGkgnCPb197XU9oSj1SMyY5EgASv6G5qpCml4CUg2+BcF9vXk5dSjxJMyYxEQAKwKCnq4+WmICGhG91cV5jXk5T" +
    "SjxAMyYqEAACwp+VrI+FmX93hG5ncV5YXk5ISjw3MiUiDwAAwp+DrY51mX5nhW1ZcV1LXk0+SjsuMiUZDwAAw55xro1kmn1ZhW1McVxAXk0zSjslMiUQDgAAxJ1croxSmn1IhWw9cVwyXkwmSjsZMi" +
    "UCDgAAxZ1Fr4w8m3w0hmwrcVsiX0wXSjoIMiUADQAAxpwvsIsom3whhmsacVsRXksFSjoAMiUADQAAvIy/qH2rlm+Zg2CGcFFyXkJgSjJMMxwzEwANv4ysqn2bl2+KhGB4cFFnXkJWSzJDMxwsEgAE" +
    "wIucq32MmG99hGBtcVFcXkJNSzI7MxwlEgAAwYuLrHx9mG5vhF9gcVBRX0JDSjEyMxwdEQAAwop7rHttmW1hhF9UcVBGXkI5SjEqMxwVEQAAw4pqrXtemW1ThV5HcVA7XkEvSjEhMxwLEAAAw4lXrn" +
    "pNmm1DhV45cU8uXkEjSjEVMxwAEAAAxIlCrno6mmwyhV0pcU8fXkEUSjEEMhwADwAAxYgvr3oommwhhV0ZcU8PXkADSjEAMhwADwAAvHiyqGugll6Og1F8cERrXjZZSyZGNA8vFAAHv3ehqmuQl16B" +
    "hFFwcURgXzZQSyc+NBAnEwAAwHeSq2qDmF51hFFlcURWXzZHSyc2NBEhEwAAwXeDq2p1mF5ohFFacUNMXzY+SycuMxIZEgAAwXdzrGpnmF5bhFBOcUNBXjY0SyclMxIREgAAwndkrGpZmV1OhFBDcU" +
    "M3XjYrSicdMxMGEQAAwnZTrWlJmV1AhFA1cUMrXjYgSicRMxMAEQAAw3ZArWk3mV0vhVAmcUMdXjYRSicBMxMAEQAAxHYvrmknmVwghU8YcUIOXjYBSicAMxMAEQAAvWClqFaUlkuEgz9zcDNiXydS" +
    "SxhANAAqFQACv2GWqlaGl0t3hEBocTRYXyhJSxk4NAAjFAAAwGGIq1Z6mEtshEBecTRPXyhBSxkxNAEcFAAAwGF6q1ZtmExghEBTcTRGXyg5SxopNAIUEwAAwWFsq1ZgmEtUhEBIcTU8XikwSxohNA" +
    "MLEwAAwWFerFZTmEtJhEA+cDUyXiknShsZMwQBEwAAwWFOrFZFmEs8hEAycDUnXikcShsNMwUAEgAAwmE9rVY1mUsthEAkcDUaXikPShwAMwYAEgAAwmAurVYnmUsghEAXcDUNXikAShwAMwYAEgAA" +
    "vUSZqDuJljJ6gyhqcR1aXxBLSwA6NQAkFgAAvkWKqjx8lzNuhClgcR9RXxNDSwAyNQAeFQAAv0V+qj1wlzRkhCpWcSBJXxQ7SwIsNAAXFQAAwEZxqj1llzVZhCtNcSFAXxUzSwQkNAAPFAAAwEdkqz" +
    "5ZlzVOhCxDcCI3XhYrSwYdNAAFFAAAwEdYqz5OlzZEhCw5cCIuXhcjSgcUNAAAFAAAwUdKqz5AmDY4hC0ucCMjXhgYSgkIMwAAEwAAwUc7rD8ymDYqhC0icCMXXhkLSgoAMwAAEwAAwUcurD8mmDcf" +
    "hC0WcCQMXhkASgsAMwAAEwAAvRqNqBB+lgRwgwBhcQBSXwBETAA0NQAfFgAAvhuAqhNylwplhABYcQBKXwA8SwAtNQAZFgAAvx50qhdolw5chANPcQBCXwA2SwAnNQASFQAAvyFpqhpdlxJSgwdGcA" +
    "A6XgAuSwAgNAAJFQAAvyNdqhxTlxVIgws9cAAyXgAmSwAYNAABFQAAwCVSqh5Ilxc/gw41cAIqXgAfSgAQNAAAFAAAwCZGqx89lxg0gxAqcAUgXgAVSgAENAAAFAAAwCY4qyAwlxoogxIfcAcVXgAI" +
    "SgAAMwAAFAAAwSctqyEllxsegxMVcAkKXgAASgAAMwAAFAAAldr4hcLedq3GZpetVoGUR21+NlZlITxIABcimtjficHIeqyyaZacWYCGSWxxN1ZaITw/ABcbntfJjMC0fKuha5WMWn94SmtlOFVQIj" +
    "s4ABcUodWyj76gfqmObZR8XH5qS2pZOVRGIjsvABcMo9Sbkb2LgKh8bpJsXH1cTGlNOVQ7IjomABYDptOGk7x4gadrb5FcXXxOTGlBOlMxIzoeABYAqNJtlbthg6ZWcJBKXnw+TWgyOlIlIzkSABYA" +
    "qtFRl7pHhKU/cZA2X3ssTmciO1IVIzkBABYArNA3mLkwhaUqco8iX3oaTmcQO1IDIzkAABYAmcPoia/Qepy5aoiiWnSLSmF2OU1eJDRDAA4dnsLRja68fZunbIeSXHN+TGFqOkxUJDQ6AA4WocG9kK" +
    "2pf5qXboaEXXNxTWBfO0xLJTMzAA4Po8CokayWgZmGb4V1XnJkTV9TO0tBJTMrAA4Gpb+Tk6qEgph1cIRmXnFWTl9IO0s3JTMiAA4Ap75/lalxg5dlcYNXX3BKTl48PEotJTIaAA4Aqb1olqlchJZS" +
    "coJGYG86T10vPEohJTINAA4Aq7xOmKhFhZU8coIzYG8pT10fPEkSJTIAAA4ArLw3macwhpUpc4EhYG4ZT1wPPEkBJTIAAA4AnK/ajJ3DfYyubHqZXGiDTFdvO0NYJiw+AwMYoK7Fj5ywf4udbnmKXm" +
    "d2TlZjPENOJiw2AgQRo66ykpuggYuPcHl8X2dqTlZZPENGJywvAQQJpa2fk5qOgop/cXhuX2ZeT1VOPUI8JysnAAQBp6yLlJp8g4lvcXdgYGVRT1VDPUIzJyseAAUAqKt5lZlshIhfcnZSYGVFT1Q4" +
    "PUIpJysWAAUAqqpjl5hYhYdOc3VCYWQ3UFQsPUEeJysJAAUAq6lMmJdDhoY6c3UxYWQnUFMdPUEPJysAAAYArKk3mZcvhoYoc3QgYWMYUFMNPUEAJysAAAYAoJrLj4u2f3yjb2uPXlt7TktnPTpSKC" +
    "M5BgATo5q4koqlgXuTcGuBX1tuT0tdPjlJKCMxBQALpZmnk4mWg3qGcWp0YFpjUEtTPjlAKCMqBAADppmVlImFg3p3cmpnYVpYUEpJPjk4KCMjAwAAqJiDlYh1hHlocmlaYVlMUEo+PjkvKCMaAwAA" +
    "qZdylodmhXhac2lNYVlBUEo0PjkmKCMRAgAAqpdfl4dUhnhKc2g/YVgzUUkoPjgaKCMEAQAAq5ZJmIZAhnc3dGcuYlglUUkaPjgMKCMAAQAArJY2mYYuh3cndGcfYlcWUUkLPjgAKCMAAQAAooa+kX" +
    "iqgWuYcF2FYE5yUEBgPi9MKhk0CQAOpYask3iag2uKclx4YU5nUUBWPy9DKhksCAAGpoaclHiMhGp9clxtYU5dUT9NPy87KRomBwAAp4WMlXd9hGpvc1xhYU1SUT9DPy8zKRoeBgAAqIV8lnduhWli" +
    "c1tUYk1HUT86Py8rKRoWBQAAqYRsl3ZghWlVc1tJYk08UT8wPy8iKRsNBQAAqoRal3ZPhmlFdFo7YkwwUT8lPy8XKRsABAAAq4NGmHU9h2g1dFosYkwiUT4XPy8IKRsABAAArIM2mXUth2gmdFoeYk" +
    "wVUT4JPy8AKRsABAAAo3OykmefgluOck58YUFrUTRZQCRGKw0vCwAJpnOhlGeQhFuBc05wYkFgUjRQQCU+Kw4oCgABp3OSlWeDhVt1c05mYkFWUjRHQCU3Kg8hCQAAqHODlmd1hVtoc05aYkFMUjQ+" +
    "QCUvKhAaCAAAqXN0lmZohVpcc05PYkFCUjQ1QCUmKhASBwAAqXJml2ZahlpPdE5EYkE4UjQsQCYeKhEIBwAAqnJVmGZLhlpBdE03YkEsUjQhPyYTKhEABgAAq3JDmGU6h1oydE0pYkAfUjQVPyYEKh" +
    "IABgAArHI0mWUsh1kldE0cYkATUjQGPyYAKhIABgAApV6mk1OUg0mEcz5zYjJjUiVSQBZALAAqDAAEp16WlVOGhUl4cz5oYjJZUiZKQRc5KwAjCwAAqF6IllR6hUptdD5eYzNQUidCQBgyKwAdCwAA" +
    "qV57llRthUphdD5UYzNGUic5QBkqKwAWCgAAqV9tl1RhhUpVdD5JYzM9UicxQBkiKwINCQAAql5gl1RVhkpKdD4/YjM0UigoQBoaKwMDCQAAql5Rl1RHhkk9dD4zYjMpUigeQBoPKgQACAAAq15BmF" +
    "Q4h0owdD8nYjMdUigSQBoBKgQACAAAq14zmVQrh0kjdD8bYjMRUigEQBsAKgUACAAApkSZlDuJhDJ6cyhqYx1bUxBLQQA6LAAlDgAAqEWLljx8hTNvdClgYx9SUxJDQQAzLAAfDQAAqUV/lj1xhjRl" +
    "dCpXYyBJUxQ8QQItLAAYDAAAqUZylz1mhjVadCtOYyFBUxU0QQQlLAARDAAAqUdmlz5ahjVPdCxEYyI4UhYsQQYeKwAHCwAAqkdalz5PhjZFdCw6YyIvUhckQAcWKwAACwAAqkdMlz5ChjY5dC0wYy" +
    "MlUhgaQAkLKwAACgAAq0c+mD81hjYtdC0kYyMaUhgOQAkAKwAACgAAq0cymD8qhzYidC0aYiMPUhkCQAoAKwAACgAApyKOlRh/hQ1xdABiYwBTUwBFQgA1LQAgDwAAqCKBlhpzhhFmdQVZZABLUwA9" +
    "QgAuLQAaDgAAqSR2lxxphhRddQlQYwBDUwA3QQAoLAATDQAAqSdqlx9ehhdTdA1HYwE7UwAvQQAhLAALDQAAqShflyFUhhlKdBA/YwQzUwAoQQAaLAACDAAAqilUlyJKhhtAdBI2YwYrUgAgQQASLA" +
    "AADAAAqipIlyM+hhw2dBQsYwkiUgAXQAAGKwAADAAAqys7mCQyhh0qdBUhYwsXUgALQAAAKwAACwAAqysxmCUohh4hdBYYYwwNUgAAQAAAKwAACwAAbc/2YbncVqXESpCrPXuTMGh9IVJkDDlIABUi" +
    "dM7daLjGXKSxT4+bQXqFNGdwJFJaDjk/ABUceszIbLezYKOgUo6MRHp4NmZlJlFQDzg4ABUVfsuycLWfYqGOVI18RXlqN2ZZJ1FGEDgwABUNgcqcc7SMZaB8VoxsR3hdOWVNKFA8ETgnABUEhMiHdb" +
    "N5Z59sWIteSHdPOmRCKU8yEjceABUAh8dveLJjaZ5YWYpMSnZAO2M0Kk8mEzcTABUAisdWerFMa55DW4k5S3UvPGMlK04YEzcEABUAjMY/fLE4bJ0wW4kpS3UgPGIWK04JEzYAABUAdrrmaqfOXpW4" +
    "UYKhRG+LN111KEleFDFDAAsdfLnQb6a6Y5SmVYGSR259OVxpKUlUFTE7AAwXgLi8c6WpZZOXV4CESG5xOlxfKkhLFTEzAAwQhLeodaSWZ5KGWX91Sm1kPFtTK0hBFjArAAwHhraUd6OEaZF1Wn5mS2" +
    "xXPFtILEc3FjAjAA0AibWAeaJza5BmW35YTGtLPVo9LUcuFzAaAA0Ai7Rqe6FfbI9UXH1ITWs8PlkwLUYjFzAPAA0AjbRTfaBJbo9AXXw2TmosP1kiLkYVFzABAA0Aj7M+f6A2b44vXnwnTmoeP1kU" +
    "LkYGFy8AAA0AfafYcJbCZIatVnWYSGOCO1NuLEBYGCk+AAAZgqbEdJWwZ4WdWXSJS2N2PVJjLUBOGSk2AAEShaaxd5WfaYWOW3R8TGJqPlJZLkBGGSkvAAIKiKWfeZSOa4R+XHNuTWJeP1FOLj89Gi" +
    "knAAMCiqSMe5N9bINvXXJgTmFSP1FDLz8zGikfAAMAjKN6fJJtbYJgXnFTTmFGQFE5Lz8qGikXAAQAjqNmfpFab4FQX3FET2A5QFAtMD4fGikLAAQAkKJQf5FGcIE9YHA0UGAqQVAfMD4SGikAAAUA" +
    "kaI9gJE1cYEtYHAlUF8cQU8SMD4DGikAAAUAg5TKdYW1aHaiWmeOTFd6P0hnLzdSHCA5AAAUh5O3eISka3aTXGaATlduQEhcMDdJHCExAAANiZOneoSVbXWFXmZ0T1ZjQUdTMTZBHCEqAAAFi5KVfI" +
    "OFbnV3X2ZnUFZYQUdJMTY4HSEjAAAAjZKEfYN2b3RoX2VbUFZNQkc/MTYvHSEbAAAAjpFzfoJncHRbYGROUVVCQkc1MTYmHSESAAAAkJFhgIFWcXNLYWRAUVU1QkYqMjYcHSEGAAAAkZBNgYFDcnM6" +
    "YWMxUVQnQ0YdMjYPHSEAAAAAkpA8goEzcnIsYmMkUlQaQ0YQMjUBHSEAAAAAh4G9eXSqbGeYXlmFT0tyQT1gMixMHxY0AAAPioGrfHSabmeJX1l4UUtnQj1WMi1DHxctAAAHjIGcfXOMb2Z9YFltUU" +
    "pdQz1NMy08HxgmAAAAjoCMfnN9cGZvYVhhUkpSQz1EMy0zHxgfAAAAj4B8f3JvcWZiYVhVUkpIQz06My0rHxkXAAAAkH9tgHJhcWVWYlhJUko9RDwxMy0jHxkOAAAAkX9cgXJRcmVHYlc8UkoxRDwm" +
    "My0ZHxkCAAAAkn9KgnFAc2Q3Y1cuU0kkRDwaMy0LHxkAAAAAk346g3Eyc2QqY1ciU0kYRDwNMy0AHhkAAAAAim+xfGOfbliOYEt8UT5qQzFZNCJGIQkvAAAKjW+hfmOQcFiBYUxwUj9gRDJQNCM+IQ" +
    "spAAACj2+Tf2ODcVh1YkxmUz9XRDJINCM3IAwiAAAAkG+EgGN2cVhpYktbUz9NRTI/NCMvIA4bAAAAkG91gWNoclhcYktQUz9DRTI2NCQnIA4TAAAAkW9ngWNccldRY0tFUz85RTIuNCQfIA8KAAAA" +
    "km5XgmNNc1dDY0s5Uz8uRTIjNCQVIBAAAAAAk25Gg2I9dFc1Y0ssVD4iRTIXNCQHIBAAAAAAlG45hGIwdFcoZEsgVD4XRTILNCQAIBAAAAAAjVymflGUcUeEYjx0UzBjRSRTNRRBIgArAwAFj1yWgF" +
    "GHckd4YzxpVDFZRiVKNhU5IgAkAgAAkVyJgVJ7c0htYz1fVDFQRiVCNhYyIgAeAQAAkVx7glJuc0hiZD1VVDFHRiY6NhcrIgAXAAAAklxuglJic0hWZD1KVDI+RiYyNRgjIQAOAAAAk1xhg1JWdEhM" +
    "ZD1AVDI1RicpNRkbIQEFAAAAk1xTg1JJdEg/ZD01VDIqRicgNRkRIQIAAAAAlFxDhFI6dUgyZD0pVDIfRicUNRkEIQMAAAAAlVw3hFIudUgnZD0eVTIVRicINRoAIQQAAAAAj0SagDuKcjJ7ZChrVR" +
    "1bRxBMNwA7JAAmBAAAkUSMgjx9dDNvZSlhVR5SRxJENwA0IwAfAwAAkkV/gzxydDRlZSpYViBKRxQ9NwItIwAZAwAAk0Zzgz1ndDRbZStOVSFCRxU1NwQmIwASAgAAk0Zngz1bdDVQZStFVSE5RxYt" +
    "NgUfIwAJAQAAlEdbgz5QdDVGZSw8VSIxRhclNgcXIgAAAQAAlEdOhD5EdTY7ZSwxVSInRhgcNggNIgAAAAAAlUdAhT43dTYvZS0mVSMcRhgRNgkAIgAAAAAAlUc1hT8tdTYlZS0cVSMTRhkGNgoAIg" +
    "AAAAAAkSePgh2AdBNyZQZjVgBUSABGOAA2JQAhBgAAkyeCgx90dRZnZgtaVgBMSAA+OAAvJAAbBQAAlCl3hCBqdRheZg5RVgFESAA3OAApJAAVBAAAlCtshCJgdRtUZRFJVgU8RwAwNwAiJAANBAAA" +
    "lCxghCRVdRxLZRNAVgg0RwApNwAbIwAEAwAAlC1WhCVLdR5CZRU3VgotRwAhNwATIwAAAgAAlS5KhCZAdR83ZRYuVgwjRwAYNwAIIwAAAgAAlS49hSc0diAsZRgjVg0ZRwENNgAAIwAAAQAAli40hS" +
    "grdiEjZhgaVg8QRwIDNgAAIwAAAQAANsb0MbHaK57CI4qqGXaTDGN8AU9kADZIABMjRcTcPrDFNp2wLYmaInWEFWNwA05ZADY/ABMcT8PHRq+yPZyfMoiLJ3V4GmJlCE5QADY4ABQWVsKxTK2fQpuO" +
    "Nod8KnRqHmFZDU1GADUwABQOW8CcUKyMRpl9OoZtLXNdIWFNEE08ADUoABQFYL+IVKt6SZhtPYVeMHJQI2BCEkwzADUfABQAZL5yWKplTJhaP4ROMnFCJV81FEwnADUVABQAaL5ZXKpPT5dGQoQ8NH" +
    "EyJ18nFksaADUHABQAar1FXqk9UZc2Q4MtNXAkKF8bF0sNADQAABQATLLlRaDNPY63M3ygKWqKHll1D0ZeAC5DAAkeVrHPTp+5RI6mOXyRLmp8IllpE0VUAC87AAoXXLC7Up6oSI2WPXuDMWlwJVhe" +
    "FkVLAC4zAAoQYa+nVp2WS4yGP3p1M2hkJ1dTGEVBAC4rAAsIZa6UWZyETot2QnlnNWhXKFdJGUQ4AC4jAAsAaK2BXJt0UYpnRHlZN2dLKlY+GkQvAS4bAAwAa6xsX5pgU4pVRXhKOGc+K1YyHEQkAi" +
    "4RAAwAbqxWYppMVYlDR3c5OWYvLFUkHUMXAy4DAAwAcaxDY5k7Vok0SHcrOmYiLVUYHUMKAy0AAA0AWqDXUZDBSICsPXCXMl+CJ09uGT1YBCc+AAAaYaDDV4+vTYCcQW+JNV91KU9jGz1OBSc2AAAT" +
    "ZZ+xWo+fUH+ORG98N15qK09ZHT1GBicvAAELaZ6eXY6OUn5+Rm5uOV5eLU5OHj09BycoAAEDbJ2MYI19VH5vR21hOl1SLk5EHzw0CCcgAAIAbp17YoxuVn1hSW1UO11HL006HzwrCCcYAAMAcZxnZI" +
    "xcV3xRSmxGPFw6L00uIDwhCScNAAMAc5xTZotJWXxAS2w2PVwsME0iITwUCScAAAQAdZtCZ4s5WnwyTGwpPlwgMUwWITsHCicAAAQAZI7JWoC1UHKiRWONOVR6LUVnIDRSDB45AAAVaY63Xn+kU3GS" +
    "R2KAO1NuL0VcITRJDR8xAAANbI2mYX+VVnGFSWJ0PVNjMERTIjRBDR8rAAAFb42VY36FV3B3SmJoPlNYMURJIjQ4Dh8jAAAAcYyEZX52WXBpTGFbPlJNMkQ/IzQwDh8cAAAAc4x0Zn1oWm9cTWFPP1" +
    "JCMkQ2IzQnDh8TAAAAdYtiaH1XW29NTmBCQFI2M0QrJDQdDyAIAAAAd4tPaXxGXG49TmAzQVEpM0MfJDMRDyAAAAAAeIpAa3w3XW4vT2AnQVEeNEMTJDMEDx8AAAAAbHy9YHCpVmOXSlaEPkhyMjpg" +
    "JCpMEhQ0AAAQcHyrZHCaWGOJTFZ4QEhnMzpWJSpDEhUtAAAIcnycZm+MWmN9TVVtQEhdNDpNJis8EhYmAAABdHyMZ299W2JwTlVhQUhSNDpEJis0EhYfAAAAdXx9aG5vXGJjT1VVQkdINTo7JissEh" +
    "cYAAAAd3tuam5iXWJWUFRKQkc+NToyJiskEhcPAAAAeHtda25SXmFIUFQ+Q0czNjonJysaEhcDAAAAenpMbG1CX2E6UVQwQ0cmNjocJysNEhgAAAAAe3o+bW01YGEtUVQlQ0cbNjoRJysBEhgAAAAA" +
    "cWyxZWCfWlWOTkl8QjxqNS9ZJyBGFQcwAAAMdGyhaGCQXFWBUElwQzxgNjBQKCE+FQkpAAADdmyTaWCDXVV1UElmQz1XNzBIKCE3FQoiAAAAd2yEamB2XlVpUUlbRD1NNzA/KCIwFQsbAAAAeGx2a2" +
    "BpX1VdUUlQRD1DNzA3KCIoFQwUAAAAemtobGBdX1VSUklGRD06NzEuKSIgFQ0LAAAAe2tZbWBOYFVFUkk6RT0vNzEkKSMXFQ4AAAAAfGtJbl8/YVQ3U0guRTwkODAZKSMKFQ4AAAAAfWs8b18zYlQr" +
    "U0gjRTwaODEOKSMAFQ8AAAAAdlmmak+UXkWFUTp0RS5jOCJTKhJBGAArAAAHeFqWbE+HYEZ4UztpRi9ZOSNKKhQ6GAAlAAAAelqJbVB7YEZuUztfRjBROSRDKhUzGAAeAAAAe1p8bVBvYUZiUztVRj" +
    "BIOSU7KhYsGAAXAAAAe1pvblBjYUZXVDtLRjA/OSUyKhckFwAPAAAAfFpib1BXYkZNVDtBRjA2OSUqKhccFwAGAAAAfVpUb1BKYkZAVDs2RjEsOSYhKhgTFwEAAAAAflpGcFA8Y0Y0VTwrRzEhOSYW" +
    "KhgGFwIAAAAAf1o6cVAxY0YpVTwhRzEXOSYMKhkAFwMAAAAAekSabTuKYTJ7VChsRx1cOw9NLAA8GgAnAAACfESMbzt+YjNwVSlhSB5TOxJFLAA1GgAgAAAAfUWAbzxzYzRmVSpYSB9LOxQ9LAEuGg" +
    "AaAAAAfUZ0cD1nYzRcVStPSCBCOxU2LAMnGQATAAAAfkZocD1cYzVRVStGSCE6OxYuLAUgGQALAAAAfkZdcD5SYzVIViw9SCIyOxcmLAcYGQACAAAAf0dQcT5GZDU8ViwzSCIoOxcdLAgPGQAAAAAA" +
    "gEdCcj45ZDUxViwoSCIeOhgTKwkCGAAAAAAAgEc4cj4vZTYnVi0fSCMVOxkJKwoAGAAAAAAAfSqQcCGBZBhzVwxkSQBVPABHLgA3HAAiAAAAfiqDcSJ1ZRpoVw9aSgJNPQA/LgAwHAAcAAAAfyx4cS" +
    "RrZRxfVxJSSgVFPAA4LgAqGwAWAAAAfy1tcSVhZR1VVxRJSQg9PAAxLQAjGwAPAAAAfy9icidWZR9MVxZBSQs1PAAqLQAcGwAGAAAAgDBXcihNZSBDVxc4SQwuPAAjLQAVGgAAAAAAgDBLcihCZSE5" +
    "VxgvSQ4lPAIaLQALGgAAAAAAgTE/cyk2ZSIuVxklSQ8bPAMQLQAAGgAAAAAAgTE2cyotZiIlVxodSRATPAQFLQAAGQAAAAAAAL3yAKnYAJfBAISpAHGSAF98AEtkADRIABEjALvaAKjEAJavAIOZAH" +
    "CEAF5vAEtZADQ/ABIcAbrGAaexAJWfAIKLAHB3AF5kAEpQADM4ABIWAbmxAaafAZSOAIF8AG9qAF1ZAEpGADMwABMPCLicB6SMAZN9AYBtAG5dAF1OAEk9ADMoABMGH7eJGqR7EpJtA4BfAG1RAFxD" +
    "AEkzADMgABMAK7ZzJaNnHZFcEH9PAW1DAFw3AEkpADMWABMANLVcLaJTJJFJGH4/CGw0AFspAEgcADIJABMAObVKMaJCKJA6HH4yDWwoAFseAEgRADIAABQAAarjAZnLAYi2AHefAGaJAFV0AEJdAC" +
    "xCAAYeAanOAZi4AYilAXeQAGV8AFVpAEJUACw7AAgYG6m7GZenE4eVCHaDAWVwAFReAEJLACwzAAkRKqinJZaWHoaGFHV1BmRkAFRUAEJCACwsAAkJM6eULZWFJYV2G3RnDmRYAVNJAEE4ACwkAAoA" +
    "OqaCM5V0KoRnIHRaFGNMBFM/AEEvACwcAAsAQKVuOJRiL4RXJHNLGGI/CVMzAEElACwSAAsARaRZPJNPM4NGJ3M8G2IxDVImAEEZACwFAAsASKRIP5M/NYM4KXIvHWImEFIcAEAOACwAAAwAHJrWG4" +
    "rAGHurEGuWBVuBAExtADpXACQ+AAAaLpnCKoquJHubG2uIEVt1BEtiADpOACU2AAATN5mwMomeK3qNIWp7F1tqCktZADpGACUvAAAMPpieN4iOL3l+JmpuG1peD0tOADo9ACUoAAADQ5eMO4d+M3lw" +
    "KWlhHlpTEktEATo0ACUgAAEASJZ8P4duNnhiLGlVIFlIFEo7AzosACUYAAIATJZpQ4ZdOXhTLmhHI1k7F0owBTkiACUOAAIAT5VVRoZMPHdCMGg5JVguGEokBzkWACUBAAMAUpVGSIU9PXc1MmctJl" +
    "gjGUkZCDkLACUAAAMAOonJNHu0Lm2hJl+NHFB5EkJmAzFRABw5AAAWQoi2O3qjNG2SK1+AIVBtFkJcBjFJABwyAAAOR4imP3qVN22FLl50I1BjGEJTCTJBAB0rAAAGS4eVQ3mGOmx3MF5oJlBYGkJJ" +
    "CzI5AB0kAAAAT4eFRnl3PWxpMl1bJ09NHEFADTIwAB0cAAAAUoZ1SHhoP2tdNF1QKU9DHUE3DjIoAB4UAAAAVYZkS3hZQWtONl1DKk84HkEsDzEeAB4JAAAAV4VSTXdIQ2o/N1w1K04rH0EhEDETAB" +
    "4AAAAAWYVDTnc7RGozOFwqLE4hIEAWETEHAB4AAAAASXi8QmypOl+XMVKEJ0VxHTdfEChMABE0AAART3irRmyZPl+JNFJ4KkVmHzhWEihDABMtAAAJUnicSWuMQF99NlJtK0VdIDhNEyk8ABMnAAAB" +
    "VHiNS2t+Ql9wN1JhLUVTIThEFCk0ABQgAAAAV3d9TWpwQ15jOVJWLkVJIjg7FCksABUYAAAAWXdvT2pjRV5XOlFLLkU/IzgzFSkkABUQAAAAW3ZfUWpURl5KO1E/L0Q0JDgpFSkbABYFAAAAXXZOUm" +
    "pESF48PFEyMEQoJDceFikQABYAAAAAXnZBU2k4SV0wPVEoMUQeJTcUFikEABYAAAAAU2mxSl2fQlKOOEZ8LjpqIy1ZFx5HAwQwAAANV2mhTl2QRVKBOkZwMDpgJS5QGB8/BAYpAAAEWWmTUF2ERlJ1" +
    "PEdmMTpXJi5IGB84BAgjAAAAW2mFUV12R1JpPEdbMTpNJi5AGSAwBAkcAAAAXWh3Ul1qSFJdPUZRMjpEJy43GSAoBAoUAAAAXmhpVF1dSVJSPkZHMjs7Jy8vGSEhBAsMAAAAYGhaVV1QSlJGP0Y7Mz" +
    "owJy8lGSEYBAwBAAAAYWhLVlxBS1I5P0YvMzolKC8bGiEMAw0AAAAAYmg+V1w2TFIuQEYlNDocKC8RGiEBAw0AAAAAW1emUU2VSEOFPjh0My1jKSFTHBBBCQAsAAAIXliXVE6HSkR5PzlpNC5aKSJL" +
    "HBI6CQAlAAAAX1iKVU57S0RuQDlgNS5RKiNDHBMzCQAfAAAAYVh9Vk5vTERjQTpWNS9IKiM7HBQsCAAYAAAAYlhwV05jTERYQTpMNS8/KiQzHRUlCAAQAAAAY1hjWE5YTURNQTpCNi83KiQrHRYdCA" +
    "AHAAAAZFhWWU5LTkRCQjo4Ni8tKiQiHRcUCAAAAAAAZVhHWk4+T0Q2QzosNi8jKyUYHRcIBwEAAAAAZlg8W04zT0QrQzojNzAaKyUOHRcABwEAAAAAYUSbVzuLTTJ8QyhsOB1cLQ9NIAA8DgAnAAAD" +
    "ZESNWTt+TzNxRCliOB5TLRJFIAA1DgAhAAAAZUWBWjxzTzNnRCpZOB9LLRM+IAEvDQAbAAAAZUV1WjxoUDRcRCpQOCBDLRU2IAMoDQAUAAAAZkZpWz1dUDRSRCtHOCE7LRYvHwUhDAAMAAAAZ0ZeWz" +
    "1TUDVJRCs+OSEzLRYnHwYaDAADAAAAZ0ZRXD1HUTU+RSw0OSIpLRcfHwcQCwAAAAAAaEZEXT07UTUyRSwpOSIgLRcVHwgECwAAAAAAaUY5XT4xUjUpRSwhOSMXLRgMHwoACwAAAAAAZiyRWySCURt0" +
    "RhBlOwJWMABIIwA3EQAjAAAAaC2EXSV2Uh1pRxNbOwVNMABAIgAxEQAdAAAAaC95XSZsUx5gRxVTOwhGMAA5IgAqEAAXAAAAaTBuXShiUiBWRxdKOws+LwAyIgAkEAAQAAAAaTFjXSlYUiFNRxhCOw" +
    "02LwArIgAdDwAHAAAAaTJYXipOUyJERxk6Ow8vLwIkIQAWDwAAAAAAajJNXipDUyM6RxowOxAmLwMbIQAMDgAAAAAAajNBXys4VCMvRxsnOxEdLwUSIQABDgAAAAAAazM3XysuVCQnRxseOxIVLwYI" +
    "IQAADgAAAAAAALXxAKLXAJDAAH6oAGyRAFt7AEhjADFIABAjALPZAKHDAJCuAH6YAGyDAFtvAEhZADE/ABAdALLFAKCxAI+eAH2KAGt3AFpkAEdQADE4ABEWALGxAJ+eAI6NAHx8AGpqAFpZAEdGAD" +
    "EwABIPALCcAJ6MAI19AHttAGpdAFlOAEc9ADEoABIGAK+KAJ17AIxuAHtgAGlSAFlEAEY0ADEgABIAAK51AJxpAItdAHpRAGlEAFg4AEYqADEXABMAAK1fAJtVAItMAHpBAGg2AFgrAEYeADELABMA" +
    "AK1NAJtGAIs+AHk1AGgrAFghAEYUADEAABMAAKPiAJLKAIO1AHKeAGGIAFF0AD9dACpCAAUfAKPNAJK4AIKkAHKQAGF8AFFoAEBTACo7AAYYAKK6AJGnAIKVAHGCAGFwAFFeAD9LACozAAcRAKGnAJ" +
    "CWAIGFAHB1AGBkAFBUAD9CACosAAgJAKCUAI+FAIB2AHBnAGBYAFBJAD85ACokAAkBAJ+DAI91AH9oAG9bAF9NAFA/AD8wACodAAkAAJ5vAI5jAH9YAG9MAF9AAE80AD4mACoTAAoAAJ5bAI1RAH5I" +
    "AG4+AF4zAE8oAD4bACoHAAsAAJ1LAI1DAH47AG4yAF4oAE8eAD4RACoAAAsAAJTVAIW/AHarAGeVAFeBAEhtADdXACI+AAAaAJPBAIStAHabAGeHAFd0AEhiADhOACM2AAAUAJOwAISeAHaNAGZ7AF" +
    "dqAEhZADhGACMvAAANAJKeAIOOAHV+AGZuAFdeAEhPADg9ACMoAAAEAJGNAIJ+AHRwAGViAFZTAEhFADc1ACMhAAAAAJB8AIJvAHRjAGVWAFZIAEc7ADcsACMZAAEAAZBqAYFfAHNUAGRIAFU8AEcx" +
    "ADcjACQPAAIABI9YAoFOAHNEAGQ6AFUwAEclADcYACQDAAIAEo9JDYBAA3I4AGQvAFUmAEccADcOACQAAAIAAITIAHazAGmgAFuMAE15AD9mAC9RABo5AAAWAIS2AHajAGmSAFt/AE1tAD9cAC9JAB" +
    "oyAAAPAYOmAXWUAGmFAFt0AE1jAD9TAC9BABsrAAAHAYOVAXWGAWh3AFtoAE1YAD9KAC85ABskAAAADoKFDHR3BWhqAFpcAExOAD9AAC8xABwdAAAAGoF2FnRpD2ddBFpRAExEAD83AC8pABwVAAAA" +
    "IoFlHXRaFmdPC1lEAEw5AD4tAC8fABwLAAAAKYFUI3NKG2dBEVk3A0stAD4iAC8VABwAAAAALIBGJnM9HmY1FFktBksjAD4ZAC8KABwAAAAAAXS8AWioAVyWAU+EAEJxADVfACZMAA80AAASFXSrFG" +
    "iZD1yJB093AEJmADVWACZEABEtAAAKIHScHGiMF1x9D09tBEJdADZNACc8ABInAAACJnSNImd+HFxwFE9hCEJTADZFACc0ABIgAAAALHN+JmdwIFtkF09WDEJJATY8ACctABMZAAAAMHNwKmdjI1tY" +
    "Gk9MD0JAAjYzACclABQRAAAANHNgLWZVJltLHU5AEkI1BDYqACccABQGAAAAN3JQMGZGKVs9H040FEIqBjUfACcRABQAAAAAOnJDMmY6KloyIE4qFUIgCDUWACcGABUAAAAAKGaxI1ueH1COGER8Dz" +
    "hqBCtZABxHAAIwAAAOL2ahKluQJFCBHERwEzhgCCxQAB0/AAQpAAAFM2aTLVuEJ1B1H0RmFjhXCixIAB44AAYjAAAANmaFMFp3KVBqIURcFzhODCxAAB4wAAccAAAAOWZ3M1pqK1BeIkRRGTlEDi04" +
    "AB8pAAgVAAAAPGVqNVpeLU9TJERHGjk8Dy0wAB8iAAoNAAAAPmVbN1pRL09HJkQ8GzkxEC0mAB8ZAAoCAAAAQWVMOVpDMU86J0QxHDgnES0cAR8OAAsAAAAAQmVBOlo4Mk8wKEQnHTgeEi0TASADAA" +
    "sAAAAAOVamM0yVLUKFJTd0HCxjEx9TBQ9CAAAsAAAJPVaXN0yHMEJ5JzhpHixaFCFLBhE6AAAlAAABQFaKOUx8MUNuKThgHy1RFSFDBxIzAAAfAAAAQlZ9OkxwMkNjKjhWIC1JFiI7BxMsAAAZAAAA" +
    "Q1ZwO0xkM0NYKjhMIS5AFiIzBxQlAAARAAAARVZkPUxZNUNOKzhDIS43FyMsBxUeAAAIAAAARlZXPkxMNkNDLDg4Ii4uFyMjCBUVAAAAAAAASFZJQEw/N0M3LTkuIy4kGCMZCBYKAAAAAAAASVY+QU" +
    "w1OEMtLjklIy4cGCMQCBYAAAAAAAAARUObPTqLNjJ8LihtJBxdGw9NDwA8AAAoAAAER0SNQDt/ODJxLyliJR5UHBFFDwA1AAAhAAAASUWCQTx0OTNnMClZJh9MHBM+DwAvAAAbAAAASkV2QTxpOTNd" +
    "MCpQJiBDHBQ3DgIoAAAUAAAAS0VqQjxeOjRTMCpHJiA7HBUvDgQhAAANAAAATEZfQz1UOjRJMSs+JiEzHBYoDgUaAAAEAAAATUZSRD1IOzQ/MSs1JyEqHBYfDgcRAAAAAAAATkZFRT08PDQ0MisrJy" +
    "IhHBcWDggGAAAAAAAATkY7Rj0yPTUrMiwjKCIZHRgODgkAAAAAAAAATS+RRCeDPR51NBRmKgVXIABIFAA4AgAkAAAATi+FRid3Ph9qNRVcKwhOIQBBFAAxAgAeAAAATzF6RyltPiBhNRdUKwtHIAA6" +
    "FAArAQAYAAAAUDJvRypjPiJXNRhLKg0/IAAzEwAlAAARAAAAUDNkRytZPiNONBpDKg83IAEsEwAeAAAIAAAAUTRZSCtPPyNFNRs7KhAwIAMlEwAXAAAAAAAAUTROSCxEPyQ7NRsxKxEnIAUdEwAOAA" +
    "AAAAAAUjRCSSw5QCQxNhwoKxIeIAYTEgADAAAAAAAAUjU4SSwwQCUoNhwgKxMWIAcKEgAAAAAAAAAAAK7vAJvWAIu/AHqnAGiQAFh7AEVjAC9HAA4jAKzYAJvCAIqtAHmYAGiDAFdvAEVZAC8/AA8d" +
    "AKvEAJqwAIqdAHiKAGd2AFdkAEVQAC84ABAXAKqwAJmeAIiNAHh8AGdqAFZZAERHAC8wABEPAKmcAJiMAIh9AHdtAGZeAFZOAEQ9AC8pABEHAKiKAJd8AIdvAHZgAGZSAFZEAEQ1AC8hABIAAKd2AJ" +
    "ZqAIZeAHZSAGVFAFU5AEQqAC8YABIAAKZhAJVXAIZOAHZDAGU4AFUtAEQgAC8MABIAAKZQAJVJAIZBAHU4AGUuAFUjAEQWAC8CABIAAJ7hAI3JAH60AG6eAF6IAE5zAD1dAChCAAMfAJ3MAI23AH6j" +
    "AG6PAF57AE5oAD1TACg7AAUYAJy5AIymAH2VAG2CAF1wAE5eAD1LACg0AAYSAJunAIuVAHyFAGx1AF1kAE5UAD1CACgsAAcKAJqUAIqFAHt2AGxnAFxYAE1JAD05ACglAAgBAJmDAIl1AHtpAGtbAF" +
    "xNAE1AADwxACgdAAkAAJhwAIlkAHpZAGtNAFxBAE01ADwnACgUAAkAAJhdAIhTAHpKAGs/AFs1AEwqADwcACkIAAoAAJdOAIhFAHo9AGo1AFsrAEwgADwTACkAAAoAAI/UAIC+AHKqAGOVAFSAAEZt" +
    "ADVXACA+AAAbAI7BAICtAHKaAGOHAFR0AEZiADVOACE2AAAUAI6wAH+dAHGNAGN7AFRpAEZZADVGACEwAAANAI2eAH6OAHF+AGJuAFReAEVPADU9ACEoAAAFAIyNAH5+AHBwAGJiAFNTAEVFADU1AC" +
    "IhAAAAAIt9AH1wAHBjAGFWAFNJAEU8ADUtACIaAAAAAItrAH1gAG9VAGFJAFM9AEUyADUkACIQAAEAAIpZAHxPAG9GAGE8AFIyAEQnADUZACIEAAIAAIpLAHxCAG86AGAyAFIoAEQeADUQACIAAAIA" +
    "AIDIAHKzAGagAFiMAEp4ADxmAC1RABg5AAAWAH+1AHKjAGWRAFh/AEptAD1cAC1JABgyAAAPAH+mAHKUAGWEAFh0AEpjAD1TAC1BABkrAAAIAH6VAHGGAGV3AFdoAEpZAD1KAC45ABokAAAAAH6FAH" +
    "F3AGRqAFdcAEpOAD1BAC4xABodAAAAAH12AHBqAGReAFdRAElEADw4AC4pABoWAAAAAH1mAHBbAGRQAFZFAEk6ADwuAC4gABsMAAAAAH1VAHBLAGNCAFY5AEkuADwkAC4WABsAAAAAAHxIAG8/AGM3" +
    "AFYvAEklADwbAC4MABsAAAAAAHG8AGWoAFmWAE2DAEBxADNfACRMAA00AAASAHGrAGWZAFmJAE13AEBmADNWACREAA8uAAAKAHGcAGWMAFl9AE1tAEBdADRNACU8ABAnAAADAHCNAGR+AFlwAE1iAE" +
    "BTADRFACU1ABEgAAAAAHB+AGRxAFhkAExXAEBJADQ8ACUtABIZAAAAAHBwAGRkAFhZAExMAEBAADQ0ACYmABISAAAAAG9hAGNWAFhMAExBAEA2ADQqACYdABMHAAAAAG9RAGNIAFg/AEw1AEArADQg" +
    "ACYTABMAAAAAAG9FAGM8AFg0AEwsAEAiADQYACYJABMAAAAAAGSxAFieAE6OAEJ8ADZqAClZABpHAAAwAAAOAGOhAFiQAE6BAEJwADZgACpQABs/AAIqAAAGAGOTAFiEAE52AEJmADdXACtJABw4AA" +
    "QkAAAAAGOFAFh3AE5qAEJcADdOACtAAB0xAAUdAAAAAGN4AFhrAE1fAEJSADdFACs4AB0pAAcWAAAAAGNrAFhfAE1UAEJIADc8ACswAB4iAAgOAAAAAGJcAFhSAE1IAEI9ADcyACsnAB4aAAkDAAAA" +
    "AGJOAFdEAE07AEIyADcoACsdAB4PAAoAAAAAB2JCBlc6AE0yAEIpADcgACwVAB4FAAoAAAAAAFSmAEqVAEGFADZ0ACpkAB5UAA1CAAAsAAAKAFSXAEqIAEF5ADZqACtaAB9LAA86AAAmAAACA1WLA0" +
    "t8AEFvADdgACxSACBEABE0AAAgAAAADVV+CktwBUFkADdWACxJACE8ABItAAAZAAAAE1VxEEtlCkFZATdNACxAACE0ABMmAAASAAAAGFVlFEtaDkFPBDdEAC04ACItABQfAAAJAAAAHFVYGEtNEUFE" +
    "CDc5AC0vACIkABQWAAAAAAAAH1VKG0tBFUE4CzcvAC0lACIaABULAAAAAAAAIlU/HUs3F0EvDTcmAS0dACISABUCAAAAAAAAHEOcGDqMFDJ9DihtBRxdAA9OAAA9AAAoAAAFIUSOHTt/GDJxEihjCB" +
    "5UABFGAAA2AAAiAAAAJESCIDt0GzNoEylaCR9MABI/AAAvAAAcAAAAJ0V2IjxpHDNeFCpRCh9EABQ3AAIpAAAVAAAAKUVqIzxfHTNUFSpICyA8ABUwAAMiAAANAAAAKkVfJTxUHjRKFio/DCA0ABUp" +
    "AAUbAAAEAAAALEVTJjxJIDRAFys2DSErARYgAAYSAAAAAAAALUZGKDw9ITQ1GSssDiEiAhYXAAcHAAAAAAAALkY8KT00IzQsGiskDyIaAxcPAAgAAAAAAAAALjCSKSmDIyB2HBZnFAhYCgBJAAA5AA" +
    "AkAAABMTGFKyl4JSFrHhddFQpPCwBBAAAyAAAeAAAAMjJ7LCpuJiJhHhhUFQxHCwA6AAArAAAYAAAAMzNwLStjJiNYHhpMFQ4/CgAzAAAlAAARAAAANDRlLixZJyRPHxtDFRA4CgIsAAAeAAAJAAAA" +
    "NDVaLixQJyRGHxs7FhEwCgQlAAAXAAABAAAANTVOLy1FKCU8IBwyFhIoCwUdAAAPAAAAAAAANjZCMC06KSUxIB0pFxMfCwYUAAAEAAAAAAAANjY5MC0xKiUpIR0hFxMXDAcLAAAAAAAAAAAA";

const decodeBase64 = (s: string): Uint8Array => {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    const map = new Int16Array(128).fill(-1);
    for (let i = 0; i < alphabet.length; i++) map[alphabet.charCodeAt(i)] = i;
    const out = new Uint8Array(Math.floor((s.replace(/=+$/, "").length * 3) / 4));
    let bits = 0;
    let acc = 0;
    let o = 0;
    for (let i = 0; i < s.length; i++) {
        const v = map[s.charCodeAt(i)];
        if (v < 0) continue;
        acc = (acc << 6) | v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out[o++] = (acc >> bits) & 0xff;
        }
    }
    return out;
};

let lut: Uint8Array | null = null;

/** CMYK components in 0..1 → RGB bytes (0..255) written into `out` at `offset`. */
export const cmykToRgbBytes = (c: number, m: number, y: number, k: number, out: Uint8Array | number[], offset = 0) => {
    const table = (lut ??= decodeBase64(LUT_B64));
    const n = GRID - 1;
    const idx = [0, 0, 0, 0];
    const fr = [0, 0, 0, 0];
    const v = [c, m, y, k];
    for (let d = 0; d < 4; d++) {
        const f = Math.min(Math.max(v[d], 0), 1) * n;
        const i = Math.min(Math.floor(f), n - 1);
        idx[d] = i;
        fr[d] = f - i;
    }
    let r = 0;
    let g = 0;
    let b = 0;
    for (let corner = 0; corner < 16; corner++) {
        let w = 1;
        let key = 0;
        for (let d = 0; d < 4; d++) {
            const bit = (corner >> (3 - d)) & 1;
            w *= bit ? fr[d] : 1 - fr[d];
            key = key * GRID + idx[d] + bit;
        }
        if (w === 0) continue;
        r += w * table[key * 3];
        g += w * table[key * 3 + 1];
        b += w * table[key * 3 + 2];
    }
    out[offset] = Math.round(r);
    out[offset + 1] = Math.round(g);
    out[offset + 2] = Math.round(b);
};

/** CMYK components in 0..1 → RGB in 0..1. */
export const cmykToRgb = (c: number, m: number, y: number, k: number): [number, number, number] => {
    const o = [0, 0, 0];
    cmykToRgbBytes(c, m, y, k, o);
    return [o[0] / 255, o[1] / 255, o[2] / 255];
};
